"use strict";
exports.__esModule = true;
exports.secondLevelEnums = exports.firstLevelEnums = void 0;
var firstLevelEnums;
(function (firstLevelEnums) {
    firstLevelEnums[firstLevelEnums["/awesome/"] = 0] = "/awesome/";
    firstLevelEnums[firstLevelEnums["/bag/"] = 1] = "/bag/";
    firstLevelEnums[firstLevelEnums["/asshole/"] = 2] = "/asshole/";
    firstLevelEnums[firstLevelEnums["/because/"] = 3] = "/because/";
    firstLevelEnums[firstLevelEnums["/bye/"] = 4] = "/bye/";
    firstLevelEnums[firstLevelEnums["/cool/"] = 5] = "/cool/";
    firstLevelEnums[firstLevelEnums["/cup/"] = 6] = "/cup/";
    firstLevelEnums[firstLevelEnums["/diabetes/"] = 7] = "/diabetes/";
    firstLevelEnums[firstLevelEnums["/even/"] = 8] = "/even/";
    firstLevelEnums[firstLevelEnums["/everyone/"] = 9] = "/everyone/";
    firstLevelEnums[firstLevelEnums["/family/"] = 10] = "/family/";
    firstLevelEnums[firstLevelEnums["/fascinating/"] = 11] = "/fascinating/";
    firstLevelEnums[firstLevelEnums["/flying/"] = 12] = "/flying/";
    firstLevelEnums[firstLevelEnums["/bucket/"] = 13] = "/bucket/";
    firstLevelEnums[firstLevelEnums["/ftfy/"] = 14] = "/ftfy/";
    firstLevelEnums[firstLevelEnums["/fyyff/"] = 15] = "/fyyff/";
    firstLevelEnums[firstLevelEnums["/give/"] = 16] = "/give/";
    firstLevelEnums[firstLevelEnums["/holygrail/"] = 17] = "/holygrail/";
    firstLevelEnums[firstLevelEnums["/idea/"] = 18] = "/idea/";
    firstLevelEnums[firstLevelEnums["/immensity/"] = 19] = "/immensity/";
    firstLevelEnums[firstLevelEnums["/jinglebells/"] = 20] = "/jinglebells/";
    firstLevelEnums[firstLevelEnums["/life/"] = 21] = "/life/";
    firstLevelEnums[firstLevelEnums["/logs/"] = 22] = "/logs/";
    firstLevelEnums[firstLevelEnums["/looking/"] = 23] = "/looking/";
    firstLevelEnums[firstLevelEnums["/maybe/"] = 24] = "/maybe/";
    firstLevelEnums[firstLevelEnums["/me/"] = 25] = "/me/";
    firstLevelEnums[firstLevelEnums["/mornin/"] = 26] = "/mornin/";
    firstLevelEnums[firstLevelEnums["/no/"] = 27] = "/no/";
    firstLevelEnums[firstLevelEnums["/question/"] = 28] = "/question/";
    firstLevelEnums[firstLevelEnums["/ridiculous/"] = 29] = "/ridiculous/";
    firstLevelEnums[firstLevelEnums["/rtfm/"] = 30] = "/rtfm/";
    firstLevelEnums[firstLevelEnums["/shit/"] = 31] = "/shit/";
})(firstLevelEnums = exports.firstLevelEnums || (exports.firstLevelEnums = {}));
var secondLevelEnums;
(function (secondLevelEnums) {
})(secondLevelEnums = exports.secondLevelEnums || (exports.secondLevelEnums = {}));
